name: testsuite

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:

# I don't think that we can (safely) set TEST_JOBS=2 in the global environment,
# because on Win32 the various Makefile's `test` target is actually ./harness,
# and it would (attempt to) honour the $ENV{TEST_JOBS} setting. This won't end
# nicely as unlike BSD (etc), Win32 sockets can drop data at process exit, which
# would cause missing TAP and hence spurious test failures.

env:
  PERL_SKIP_TTY_TEST: 1
  CONTINUOUS_INTEGRATION: 1

jobs:
  #  ___           _         ___       __                    _   _
  # / __|_ __  ___| |_____  |_ _|_ _  / _|___ _ _ _ __  __ _| |_(_)___ _ _  ___
  # \__ \ '  \/ _ \ / / -_)  | || ' \|  _/ _ \ '_| '  \/ _` |  _| / _ \ ' \(_-<
  # |___/_|_|_\___/_\_\___| |___|_||_|_| \___/_| |_|_|_\__,_|\__|_\___/_||_/__/


  cygwin:
    name: "cygwin"
    runs-on: windows-latest
    timeout-minutes: 120
    env:
      CHERE_INVOKING: 1

    steps:
      # we use Cygwin git, so no need to configure git here.

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run:
          echo "$GITHUB_CONTEXT"
      - name: Dump GitHub env
        env:
          GITHUB_ENV: ${{ toJson(env) }}
        run:
          echo "$GITHUB_ENV"
      - name: Dump GitHub workspace
        run:
          echo "$GITHUB_WORKSPACE"
      - name: Set up Cygwin
        uses: tonycoz/cygwin-install-action@installpath
        with:
          packages: cygwin-devel gcc-core gcc gcc-g++ make cygwin64-w32api-headers git
          installpath: ${{ github.env.workspace }}\cygwin
      - run: git config --global core.autocrlf false
      - name: disk layout
        run: |
          Get-Volume
        shell: powershell
      - name: Checkout
        #env:
        #  PATH: c:\cygwin\bin;c:\cygwin\usr\bin;${{ env.PATH }}
        uses: actions/checkout@v2
        with:
          path: src
      - name: Configure
        shell: cmd
        run: |
          path c:\cygwin\bin;c:\cygwin\usr\bin
          sh -c "./Configure -des -Dusedevel -Doptimize=-g -DDEBUGGING"
      - name: Build
        shell: cmd
        run: |
          path c:\cygwin\bin;c:\cygwin\usr\bin
          sh -c "make -j2 test_prep"
      - name: Show Config
        shell: cmd
        run: |
          path c:\cygwin\bin;c:\cygwin\usr\bin
          sh -c "./perl -Ilib -V; ./perl -Ilib -e 'use Config; print Config::config_sh'"
      - name: Run Tests
        shell: cmd
        # Descend far enough down the cygwin yak warren, and one discovers that
        # hints/cygwin.sh sets ldlibpthname=PATH
        # Meaning that the Makefile variable LDLIBPTH is "PATH=..."
        # Meaning that the command to invoke ./runtests is PATH=... ./perl.exe
        # *Not* LD_LIBRARY_PATH or anything conventionally unix-like
        #
        # Cygwin is the slowest CI test. Breaking the abstractions described
        # above/committing this DRY violation means that we avoid needing to
        # `make -j2 test` to invoke t/TEST, and avoiding that likely saves us
        # about 40 seconds, which is nearly 1% of the total wallclock time for
        # complete all CI runs.
        run: |
          path c:\cygwin\bin;c:\cygwin\usr\bin
          sh -c "PATH=`pwd`:.:$PATH TEST_JOBS=2 ./perl.exe t/harness"
